### ISSUE TITLE
Add "total discharge" as boundary type for surface water and groundwater

### ISSUE THREAD

**Issue by leendertvanwolfswinkel** [nens/threedi-schema#92]
In the field boundary_condition_2d.boundary_type, currently allowed values are:

- 1: Water level
- 2: Velocity
- 3: Discharge
- 5: Sommerfeld
- 6: Groundwater level
- 7: Groundwater discharge

### Tasks
- [x] Add the following options in `threedi-schema`:

- 8: Discharge (total)
- 9: Groundwater discharge (total)

- [x] Make changes to `threedi-modelchecker` to allow the new 2D boundary types
- [x] Make changes to `threedi-schematisation-editor` (https://github.com/nens/threedi-schematisation-editor/blob/1f2323d1a98e36f24ddd33b1ca7b9f671318b5af/threedi_schematisation_editor/enumerators.py#L12) to make the new boundary types appear in the UI

**Comment by leendertvanwolfswinkel** [comment]
@margrietpalm please check with @GolnesaK if changes in threedi-schema are sufficient or that changes are also needed in e.g. `threedigrid-builder`
